/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef MAZEMAKER_PRIVATE_H
#define MAZEMAKER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.0.0.231"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	231
#define COMPANY_NAME	""
#define FILE_VERSION	"0.0.0.231"
#define FILE_DESCRIPTION	"fun game!"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Maze Maker"
#define PRODUCT_NAME	"Maze Maker"
#define PRODUCT_VERSION	"0.0.0.231"

#endif /*MAZEMAKER_PRIVATE_H*/
